# Generated by Django 3.2.20 on 2023-08-11 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_read',
        ),
        migrations.CreateModel(
            name='ReadPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts_by_user', to='blog.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Readpost',
                'verbose_name_plural': 'Readposts',
            },
        ),
        migrations.AddConstraint(
            model_name='readpost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_posts'),
        ),
    ]
